### ISSUE TITLE
Google Drive link does not work in README

### ISSUE THREAD

**Issue by areee** [Arjav-Patel/Vuforia-Integration-with-Meta-2#3]
Could you share a new link to your Unity Project? The current link does not work.

**Comment by Arjav-Patel** [comment]
Unfortunately, I accidentally deleted it from my drive, and don't have a way to recover it. However, the wiki goes over all the steps to make an identical project to the one that was available on the drive.

**Comment by areee** [comment]
Ok, it's a pity. :( However, thank you for this information!
